# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatBotDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWidgets
from PyQt5.QtGui import QTextCursor
import openai



# Set your OpenAI API key here
openai.api_key = "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"


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(415, 486)
        Dialog.setStyleSheet("QTextEdit {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 10px;\n"
"    padding: 10px 20px;\n"
"    color: #000000;\n"
"    font-size: 16px;\n"
"    font-family: Arial;\n"
"    line-height: 2;\n"
"\n"
"}\n"
"\n"
"QTextEdit:hover {\n"
"    background-color: #eeeeee;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    background-color: #cccccc;\n"
"    border: 1px solid #000000;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 10px;\n"
"    padding: 10px 20px;\n"
"    color: #000000;\n"
"    font-size: 16px;\n"
"    font-family: Arial;\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #eeeeee;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #cccccc;\n"
"    border: 1px solid #000000;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #000;\n"
"  color: #fff;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 10px;\n"
"    padding: 10px 20px;\n"
"    font-size: 14px;\n"
"    font-family: Arial;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #eeeeee;\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #cccccc;\n"
"    color: #009;\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    color: rgb(48, 129, 229);\n"
"    font-size: 16px;\n"
"    font-family: Arial;\n"
"    font-weight: bold;\n"
"    margin: 0;\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.interface_2 = QtWidgets.QTextEdit(Dialog)
        self.interface_2.setMinimumSize(QtCore.QSize(200, 360))
        self.interface_2.setMaximumSize(QtCore.QSize(400, 400))
        self.interface_2.setObjectName("interface_2")
        self.gridLayout_2.addWidget(self.interface_2, 1, 0, 1, 1)
        self.interface_2.setReadOnly(True)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.message = QtWidgets.QLineEdit(Dialog)
        self.message.setObjectName("message")
        self.gridLayout.addWidget(self.message, 0, 1, 1, 1)
        self.sendBtn = QtWidgets.QPushButton(Dialog)
        self.sendBtn.setObjectName("sendBtn")
        self.gridLayout.addWidget(self.sendBtn, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.sendBtn.clicked.connect(self.send_message)

        self.messages = []

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sendBtn.setText(_translate("MainWindow", "Send"))
        self.label.setText(_translate("MainWindow", "WeatherBot"))

    def generate_response(self, prompt, chat_history):
        
        full_prompt = prompt
        response = openai.Completion.create(
            engine="text-davinci-003",
            prompt=full_prompt,
            temperature=0.7,
            max_tokens=150,
            stop=None
            )
        return response.choices[0].text
    def send_message(self):
        user_input = self.message.text()
        if user_input.lower() in ['exit', 'bye', 'good bye']:
            self.message.clear()
            response = "Bye... See You Later"
        else:
            response = self.generate_response(user_input, self.messages)
            self.messages.append(("ChatBot ", response))
            
            
        self.messages.append(("You ", user_input))
        self.display_messages()

            
        self.display_messages()
    
        self.message.clear()

    def display_messages(self):
        self.interface_2.clear()
        for sender, message in self.messages:
            self.interface_2.append(f"{sender}: {message}")
        self.interface_2.moveCursor(QTextCursor.End)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
